org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

mod_id=mf3ff
mod_name=Mining Fatigue 3 Fix Fix
mod_version=1.0.0
mod_group=io.github.cyfrit
mod_authors=cyfrit
mod_description=Fix the fix for the mining speed multiplier for Mining Fatigue 3.
mod_credits=Based on glowstone314/MF3F

minecraft_version=26.3
minecraft_version_range=[26.3,)
fabric_loader_range=>=0.19.3
forge_loader_range=[65,)
neoforge_loader_range=[26.3,)
