[versions]
minecraft-snapshot = "26.3-snapshot-4"
fabric-loader = "0.19.3"
fabric-loom = "1.16.3"
forge = "26.2-65.0.4"
forge-gradle = "7.0.31"
neoforge = "26.2.0.15-beta"
neoforge-moddev = "2.0.141"

[libraries]
minecraft-snapshot = { module = "com.mojang:minecraft", version.ref = "minecraft-snapshot" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
forge-gradle = { id = "net.minecraftforge.gradle", version.ref = "forge-gradle" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
