modLoader="javafml"
loaderVersion="[1,)"
license="Unlicense"
issueTrackerURL="https://github.com/cyfrit/MF3FF/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/cyfrit/MF3FF"
logoFile="icon.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mf3ff.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
